global:
  scrape_interval: 5s

#метрики ОС
scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

#метрики php-fpm
  - job_name: 'php-fpm'
    static_configs:
      - targets: ['php-fpm-exporter:9253']

#проверка CMS
  - job_name: 'blackbox-http'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://nginx
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115

#проверка php-fpm
  - job_name: 'blackbox-phpfpm'
    metrics_path: /probe
    params:
      module: [phpfpm_status]
    static_configs:
      - targets:
        - http://nginx:9001/fpm_status
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - target_label: __address__
        replacement: blackbox:9115

#метрики MySQL
  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql-exporter:9104']
