server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://192.168.64.138:3100/loki/api/v1/push

scrape_configs:
- job_name: nginx
  static_configs:
  - targets:
      - localhost
    labels:
      job: nginx
      __path__: /var/log/nginx/*.log

- job_name: php-fpm
  static_configs:
  - targets:
      - localhost
    labels:
      job: php-fpm
      __path__: /var/log/php8.3-fpm.log

- job_name: mysql
  static_configs:
  - targets:
      - localhost
    labels:
      job: mysql
      __path__: /var/log/mysql/error.log
